version: "3.8"
services:
  db:
    image: postgres:13
    container_name: db-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: social-network
    ports:
      - "5412:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: "redis:alpine"
    container_name: cache-redis
    ports:
      - "6379:6379"

  # TODO: find why can't connect to db Error: connect ECONNREFUSED 127.0.0.1:6379
  # api:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: nestjs-api
  #   environment:
  #     JWT_SECRET: secret
  #     DB_HOST: localhost
  #     DB_PORT: 5412
  #     DB_USER: postgres
  #     DB_PASSWORD: postgres
  #     DB_NAME: social-network
  #     REDIS_HOST: localhost
  #     REDIS_PORT: 6379
  #   ports:
  #     - "3000:3000"
  #   env_file:
  #     - .env
  #   depends_on:
  #     - db
  #     - redis
  #   volumes:
  #     - .:/app

volumes:
  postgres_data:
